// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-projects.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const anon = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  if (!url || !anon) throw new Error("Supabase env not configured");
  return createClient(url, anon, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function notAuthed() {
  return {
    content: [{ type: "text", text: "Not authenticated." }],
    isError: true
  };
}
function errorResult(message) {
  return {
    content: [{ type: "text", text: message }],
    isError: true
  };
}

// src/lib/mcp/tools/list-projects.ts
var list_projects_default = defineTool({
  name: "list_projects",
  title: "List projects",
  description: "List DevOps/SRE portfolio projects the signed-in user can see. Tech leads only see projects they are allocated to; admins and stakeholders see all.",
  inputSchema: {
    status: z.enum(["on-track", "at-risk", "delayed", "completed"]).describe("Optional status filter.").optional(),
    limit: z.number().int().min(1).max(200).default(50).describe("Max rows returned.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    let q = supabaseForUser(ctx).from("projects").select("id,name,type,category,status,progress,start_date,end_date,tags").order("start_date", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-project.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
var get_project_default = defineTool2({
  name: "get_project",
  title: "Get project",
  description: "Fetch a single project by id with its team, client contacts, and latest weekly reports.",
  inputSchema: {
    project_id: z2.string().uuid().describe("Project UUID."),
    reports_limit: z2.number().int().min(0).max(20).default(3)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id, reports_limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const sb = supabaseForUser(ctx);
    const [{ data: project, error: pErr }, team, contacts, reports] = await Promise.all([
      sb.from("projects").select("*").eq("id", project_id).maybeSingle(),
      sb.from("team_members").select("*").eq("project_id", project_id),
      sb.from("client_contacts").select("id,name,email,phone").eq("project_id", project_id),
      sb.from("weekly_reports").select("*").eq("project_id", project_id).order("week_end", { ascending: false }).limit(reports_limit)
    ]);
    if (pErr) return errorResult(pErr.message);
    if (!project) return errorResult("Project not found or access denied.");
    const payload = {
      project,
      team: team.data ?? [],
      client_contacts: contacts.data ?? [],
      weekly_reports: reports.data ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-weekly-reports.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^4.4.3";
var list_weekly_reports_default = defineTool3({
  name: "list_weekly_reports",
  title: "List weekly reports",
  description: "List weekly status reports for a project, newest first.",
  inputSchema: {
    project_id: z3.string().uuid(),
    limit: z3.number().int().min(1).max(100).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const { data, error } = await supabaseForUser(ctx).from("weekly_reports").select("*").eq("project_id", project_id).order("week_end", { ascending: false }).limit(limit);
    if (error) return errorResult(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { weekly_reports: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-weekly-report.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^4.4.3";
var create_weekly_report_default = defineTool4({
  name: "create_weekly_report",
  title: "Create weekly report",
  description: "Create a weekly status report for a project. Requires admin or tech lead role (enforced by RLS).",
  inputSchema: {
    project_id: z4.string().uuid(),
    week_start: z4.string().describe("ISO date YYYY-MM-DD"),
    week_end: z4.string().describe("ISO date YYYY-MM-DD"),
    status: z4.enum(["on-track", "at-risk", "delayed", "completed"]).default("on-track"),
    summary: z4.string().default(""),
    highlights: z4.array(z4.string()).default([]),
    blockers: z4.array(z4.string()).default([]),
    in_progress: z4.array(z4.string()).default([]),
    next_steps: z4.array(z4.string()).default([]),
    indicators: z4.array(z4.string()).default([])
  },
  annotations: {
    readOnlyHint: false,
    destructiveHint: false,
    idempotentHint: false,
    openWorldHint: false
  },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const { data, error } = await supabaseForUser(ctx).from("weekly_reports").insert(input).select().single();
    if (error) return errorResult(error.message);
    return {
      content: [{ type: "text", text: `Report created: ${data.id}` }],
      structuredContent: { weekly_report: data }
    };
  }
});

// src/lib/mcp/tools/list-professionals.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z5 } from "npm:zod@^4.4.3";
var list_professionals_default = defineTool5({
  name: "list_professionals",
  title: "List professionals",
  description: "List internal team professionals (name, role, seniority).",
  inputSchema: {
    limit: z5.number().int().min(1).max(500).default(200)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const { data, error } = await supabaseForUser(ctx).from("professionals").select("id,name,role,seniority,resumo,skills,soft_skills,certifications").order("name").limit(limit);
    if (error) return errorResult(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { professionals: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-executive-summary.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.22.2";
var get_executive_summary_default = defineTool6({
  name: "get_executive_summary",
  title: "Get latest executive summary",
  description: "Return the most recent AI-generated executive summary of the project portfolio. Admins and stakeholders only.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const { data, error } = await supabaseForUser(ctx).from("executive_summaries").select("id,generated_at,payload").order("generated_at", { ascending: false }).limit(1).maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return { content: [{ type: "text", text: "No executive summary available yet." }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { summary: data }
    };
  }
});

// src/lib/mcp/tools/me.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.22.2";
var me_default = defineTool7({
  name: "me",
  title: "Who am I",
  description: "Return the signed-in user's profile and roles in this app.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const sb = supabaseForUser(ctx);
    const uid = ctx.getUserId();
    const [{ data: profile, error: pErr }, { data: roles, error: rErr }] = await Promise.all([
      sb.from("profiles").select("*").eq("id", uid).maybeSingle(),
      sb.from("user_roles").select("role").eq("user_id", uid)
    ]);
    if (pErr) return errorResult(pErr.message);
    if (rErr) return errorResult(rErr.message);
    const payload = {
      user_id: uid,
      email: ctx.getUserEmail(),
      profile,
      roles: (roles ?? []).map((r) => r.role)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ptygtpizvgtzlhmxpwpb";
var mcp_default = defineMcp({
  name: "v8-portfolio-mcp",
  title: "V8 Portfolio MCP",
  version: "0.1.0",
  instructions: "DevOps/SRE portfolio management for V8. Use `me` to check the caller's roles, `list_projects` and `get_project` to explore the portfolio, `list_weekly_reports` for a project's status history, `create_weekly_report` to add a new weekly status (admin or tech lead only), `list_professionals` for the internal team, and `get_executive_summary` for the latest AI-generated portfolio overview.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    me_default,
    list_projects_default,
    get_project_default,
    list_weekly_reports_default,
    create_weekly_report_default,
    list_professionals_default,
    get_executive_summary_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
